{"uuid": "8f357613-afd1-486b-9c26-989c66c70490", "children": ["7ade0cc8-141e-4392-82be-d5e4f1864c7e"], "befores": [{"name": "tokens", "status": "broken", "statusDetails": {"message": "TimeoutError: Код не найден в Redis по ключу ea:oukb1147@gmail.com после 10 попыток\n", "trace": "  File \"/Users/mihail/chaincheck/.venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/Users/mihail/chaincheck/.venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/Users/mihail/chaincheck/.venv/lib/python3.12/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/Users/mihail/chaincheck/.venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/mihail/chaincheck/.venv/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/mihail/chaincheck/.venv/lib/python3.12/site-packages/_pytest/fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/Users/mihail/chaincheck_new/conftest.py\", line 29, in tokens\n    code = get_verification_code()\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/mihail/chaincheck_new/redis_utils.py\", line 28, in get_verification_code\n    raise TimeoutError(f\"Код не найден в Redis по ключу {REDIS_KEY} после {retries} попыток\")\n"}, "start": 1758719994286, "stop": 1758720015774}], "start": 1758719994286, "stop": 1758720015829}